Update examples

diff --git a/examples/bash/get/org_id b/examples/bash/get/org_id
--- a/examples/bash/get/org_id
+++ b/examples/bash/get/org_id
@@ -5,6 +5,14 @@ then
   exit 1
 fi
 SERVER=${SERVER:=api}
+
+# Check for jq.
+command -v jq >/dev/null 2>&1 || {
+  echo >&2 "jq is required but not installed."
+  exit 1
+}
+
+# Get the org id.
 curl -s "https://$SERVER.getsling.com/account/login" \
   -X POST \
   -d "{\"email\": \"$1\",\"password\": \"$2\"}"\
diff --git a/examples/bash/tools/csv2shifts b/examples/bash/tools/csv2shifts
--- a/examples/bash/tools/csv2shifts
+++ b/examples/bash/tools/csv2shifts
@@ -1,30 +1,25 @@
 #!/bin/bash
+set -e
 
 # Validate arguments.
-if [ $# -ne 3 ]
+if [ $# -ne 2 ]
 then
-  echo "./csv2shifts <email> <password> <csv>"
+  echo "./csv2shifts <token> <csv>"
   echo "csv format: start,end,location name,position name,email"
   exit 1
 fi
 SERVER=${SERVER:=api}
 
-# Login.
-token=$(
-  curl -is "https://$SERVER.getsling.com/account/login" \
-    -X POST \
-    -d "{\"email\": \"$1\",\"password\": \"$2\"}" \
-    -H "Content-Type: application/json" \
-    -H "accept: */*" | \
-  grep "^authorization: " | \
-  sed "s/^authorization: //"
-
-)
+# Check for jq.
+command -v jq >/dev/null 2>&1 || {
+  echo >&2 "jq is required but not installed."
+  exit 1
+}
 
 # Get a concise description of positions and locations.
 groups=$(
   curl -Gs "https://$SERVER.getsling.com/users/concise" \
-    -H "Authorization: ${token//[$'\t\r\n ']}" \
+    -H "Authorization: $1" \
     -H "accept: */*"
 )
 
@@ -88,7 +83,7 @@ do
     sed "s/position-value/$position_id/" |
     sed "s/user-value/$user_id/"
   )
-done < $3
+done < $2
 
 # Upload the shifts.
 body="[${results:1}]"
@@ -96,5 +91,5 @@ curl "https://$SERVER.getsling.com/shifts/bulk" \
   -X POST \
   -d "${body//[$'\t\r\n ']}" \
   -H "Content-Type: application/json" \
-  -H "Authorization: ${token//[$'\t\r\n ']}" \
+  -H "Authorization: $1" \
   -H "accept: */*"
